model:
  name: "isolation_forest"
  random_state: 42

# hyperparameters:
#   n_estimators: [100, 200, 300]
#   contamination: [0.1, 0.15, 0.2]  # 预期的异常比例
#   max_samples: [auto]
#   max_features: [1.0]  # 使用所有特征
hyperparameters:
  n_estimators: [200]
  contamination: [0.04]  # 预期的异常比例
  max_samples: [auto]
  max_features: [1.0]  # 使用所有特征

data:
  train_path: "Data/processed/splits/train.parquet"
  val_path: "Data/processed/splits/val.parquet"
  features_to_exclude: [ "anomaly_label"]

output:
  model_path: "src/models/isolation_forest_best.joblib"
  validation_report_path: "src/model_report/isolation_forest"