sliding_window:
  window_size: 60  # seconds
  step_size: 10   # seconds
  anomaly_threshold: 0.3  # 30% overlap required for anomaly labeling

paths:
  anomaly_dict: "Data/interim/Anomaly_Data/anomaly_dict.pkl"
  input_dir: "Data/processed/lsmt/standerScaler"
  output_dir: "Data/processed/lsmt/windows"
  reports_dir: "experiments/reports/lsmt"

processing:
  chunk_size: 100000  # Number of rows to process at once
  save_intermediate: true  # Whether to save intermediate results