# Data paths
paths:
  input_dir: 'Data/processed/lsmt_timeFeatures/add_timeFeatures'
  output_dir: 'Data/processed/transform/slidingWindow_noOverlap_600_600_50_0.9_0.1'
  anomaly_dict: 'Data/processed/soft_label/anomaly_dict_merged.pkl'

# Sliding window parameters
sliding_window:
  window_size: 600  # Window size in seconds
  step_size: 600    # Step size in seconds
  anomaly_step_size: 50
# 1200 300     60 10      800 150     600 100       1200 1200 200 0.6 threshold 0.5   800 800 100 0.7
# Component processing configuration
components:
  #processing_order: ['contact', 'pcb', 'ring']
  processing_order: ['contact']
# # Logging configuration
# logging:
#   log_dir: 'experiments/logs'
#   log_format: '[%(asctime)s] [%(levelname)s] [%(name)s] - %(message)s'
#   date_format: '%Y-%m-%d %H:%M:%S'

# Memory management
memory:
  gc_collect_frequency: 1  # How often to force garbage collection
  log_memory_frequency: 1  # How often to log memory usage
  threshold_gb: 2.0  # Memory threshold in GB for dynamic resource management
  max_jobs: 6  # Maximum number of parallel jobs
  batch_size: 60  # Number of segments to process in one batch