# LSTM Late Fusion Model Configuration

# Model parameters
model:
  input_size: 38  # Number of time series features
  hidden_size: 128
  num_layers: 2
  dropout: 0.3
  output_size: 2  # Binary classification
  stat_features_size: 47  # Number of statistical features

# Training parameters
training:
  batch_size: 128
  num_epochs: 150
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 4
  
  # Class imbalance handling methods (choose one):
  # Method 1: Class weights (inverse frequency weighting)
  use_class_weights: false
  
  # Method 2: Positive weight for BCE loss
  pos_weight: 5.0  # Weight for positive class (anomalies)
  
  # Method 3: Focal Loss
  use_focal_loss: true  # Set to true to use Focal Loss
  focal_loss_alpha: 0.25  # Weight for positive class (higher means more focus on anomalies)
  focal_loss_gamma: 2.0  # Focusing parameter (higher means more focus on hard examples)

  early_stopping_metric: "f1"
  early_stopping_patience: 10
  early_stopping_min_delta: 0.0001

# Data parameters
data:
  component: "contact"  # .
  sequence_length: 96  # Number of time steps in each window
  stride: 24  # Stride between consecutive windows

# Paths
paths:
  # LSTM sliding window data
  lstm_data_dir: "Data/processed/lsmt_timeFeatures/sliding_window_600s"
  # Statistical features data
  stat_features_dir: "Data/processed/lsmt_timeFeatures/statistic_features_standscaler_600s"
  # Output directory fordata/processed/statistical_features model checkpoints and results
  output_dir: "experiments/lstm_late_fusion"

# Memory management
memory:
  gc_collect_frequency: 1  # Garbage collect after each epoch 

evaluation:
  threshold: 0.3  # Classification threshold for anomaly detection (lower than default 0.5)
  auto_threshold: true  # Automatically find optimal threshold during training 