# LSTM Sequence Model Configuration

# Model parameters
model:
  input_size: 27        # Input features dimension
  hidden_size: 128      # LSTM hidden state dimension
  num_layers: 2         # Number of LSTM layers
  dropout: 0.2          # Dropout rate for regularization
  output_size: 2        # Number of output classes (normal/anomaly)

# Training parameters
training:
  batch_size: 64
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  use_focal_loss: true
  focal_loss_alpha: 0.25
  focal_loss_gamma: 2.0
  num_workers: 4

# Evaluation parameters
evaluation:
  threshold: 0.3        # Initial threshold for anomaly classification

# Data paths
paths:
  lstm_data_dir: "Data/row_energyData_subsample_Transform/slidingWindow_60"
  output_dir: "experiments/lstm_sequence"

# Data parameters
data:
  component: "contact"  # Component to use: contact, pcb, or ring
  sequence_length: 60   # Time steps per window 