# Data Cleaning
data:
  input_dir: "Data/raw"
  interim_dir: "Data/interim/Energy_Data/PCB"
  processed_dir: "Data/processed"

# Time processing
time:
  source_timezone: "Europe/Berlin"
  target_timezone: "UTC"
  timestamp_format: "%Y-%m-%d %H:%M:%S"
  gap_threshold: 15.0  #  seconds threshold for gap detection

# Data cleaning parameters
cleaning:
  remove_duplicates: true
  handle_missing_values: true
  zero_variance_threshold: 0.01  # For removing zero/near-zero variance columns
  
# Outlier detection
outlier:
  method: "iqr"  # Options: iqr, zscore
  iqr_multiplier: 1.5  # For IQR method
  zscore_threshold: 3  # For z-score method



# Columns configuration
columns:
  timestamp_col: "TimeStamp"
  station_col: "Station"
  
# Logging
logging:
  level: "INFO"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s] - %(message)s"

# Sliding window parameters
sliding_window:
  window_size: 600  # seconds
  step_size: 60     # seconds
  anomaly_step_size: 10
  overlap_threshold: 0.3  # 30% overlap required for anomaly labeling
  batch_size: 50  # 每批处理的segment数量
  max_memory_usage: 1000  # 最大内存使用量（MB）
# Data paths
paths:
  anomaly_dict: "Data/interim/Anomaly_Data/anomaly_dict.pkl"
  energy_data: "Data/interim/Energy_time_series"
  output_dir: "Data/interim/Energy_labeling_windowFeatures"
  report_file: "Data/interim/Energy_labeling_windowFeatures/Energy_ringmontage_windowFeatures.md"

# Correlation analysis
correlation:
  method: "pearson"  # pearson, spearman, or kendall
  min_correlation: 0.1  # minimum correlation to report
  top_n_features: 10   # number of top features to report

# Station mapping
stations:
  ringmontage: "Ringmontage"



# configs/preprocessing.yaml

data_paths:
  input_dir: "Data/interim/Energy_labeling_correlations"
  output_dir: "Data/processed"

feature_selection:
  correlation_threshold: 0.05  # 基本相关性阈值
  high_correlation_threshold: 0.1  # 重要特征阈值
  multicollinearity_threshold: 0.85  # 多重共线性阈值

report:
  output_path: "experiments/reports/correlation_featureMergen.md"