# Data paths
paths:
  input_dir: "Data/processed/lsmt_timeFeatures/sliding_window_600s"
  output_dir: "Data/transform/slidingWindows_transform"

# Transformer parameters
transformer:
  d_model: 256         # Transformer model dimension
  max_seq_length: 600  # Maximum sequence length (600s window)

# Processing parameters
processing:
  batch_size: 128     # Batch size for processing
  num_workers: 6      # Number of workers for parallel processing

# Memory management
memory:
  gc_collect_frequency: 1  # How often to force garbage collection 